```{r prologue, include=FALSE}
library(knitr)
library(stringr)
library(readr)
library(dplyr)
library(lattice)
library(ggplot2)
library(grid)

knitr::opts_chunk$set(warning = FALSE
                      , message = FALSE
                      , echo = FALSE
                      )

knitr::opts_template$set(
  fig.wide = list(fig.height = 4.5, fig.width = 8)
  , fig.wideX = list(fig.height = 3, fig.width = 8)
)

# a nice colour palette
myPal <- c("#8DD3C7", "#B0A8B3", "#9FB5D6", "#9EC0FA", "#DB9082")
myPal.range <- colorRampPalette(c("#FFFFFF", c(myPal[3:1] )))

# original link
link <- "https://raw.githubusercontent.com/julianhatwell/TC_SalesQuotas/master/TC_SalesQuota.csv"
# local file
#link <- "C:\\Dev\\Study\\R\\Tanc_investigation\\TC_SalesQuota.csv"
raw.data <- read_csv(link)
n = nrow(raw.data)
attach(raw.data)
raw.data$Group <- as.factor(Group)
raw.data$KSales <- Sales/1000
raw.data$KQuota <- Quota/1000
raw.data$OnTarget <- (Sales-Quota)/Quota*100
raw.data$MetTarget <- raw.data$OnTarget >= 0
attach(raw.data)
```

```{r missing_var_from_variance}
set.seed(103)
k <- 50
wndws <- cbind(lwr = 1:(n-k+1), idx = floor(k/2):(n-floor(k/2)), upr = k:n)

rsd <- as.numeric(rep(NA, n))
for (i in 1:dim(wndws)[1]) {
  rsd[wndws[i,"idx"]] <-  sd(raw.data$OnTarget[order(raw.data$Quota, decreasing = FALSE)][wndws[i,"lwr"]:wndws[i,"upr"]])
}
# bootstrap missing rolling window ends
missing <- matrix(nrow = 2, ncol = 3)
missing[1,] <- c(1
                 , wndws[1,"idx"]-1
                 , length(1:(wndws[1,"idx"]-1))
                 )
missing[2,] <- c(wndws[nrow(wndws)-floor(k/2),"idx"]+floor(k/2)+1
                 , n
                 , length((wndws[nrow(wndws)-floor(k/2),"idx"]+floor(k/2)+1):n)
                 )
# lower end
rsd[missing[1,1]:missing[1,2]] <- sample(rsd[(missing[1,2]+1):(missing[1,2]+1+k)], missing[1,3], replace = TRUE)
# upper end
rsd[missing[2,1]:missing[2,2]] <- sample(rsd[(missing[2,1]-1):(missing[2,1]-1-k)], missing[2,3], replace = TRUE)

rsd <- cbind(rsd, id = order(Quota))
raw.data$rollingSD <- rsd[order(rsd[,"id"]),"rsd"]
attach(raw.data)
```


---
title: "Investigation of fairness in sales quota setting"
author: "Julian Hatwell"
date: `r format(Sys.time(), "%b %Y") `
output: html_document
---

```{r boxplot_MetTarget, opts.label='fig.wide', eval=FALSE}
bwplot(Quota ~ factor(MetTarget) | Group
        , strip = strip.custom(bg = myPal[4])
        , between = list(x = 0.5)
        , par.settings = list(
                  plot.symbol = list(
                      col = myPal[5]
                      , pch = 19
                      , alpha = 0.75
                      , cex = 0.75)
                  , box.umbrella = list(
                      col = myPal[5]
                      , lty = 1
                      , lwd = 1.5)
                  , box.rectangle = list(
                      fill = "#FFFFFF"
                      , col = myPal[5]
                      , lwd = 2)
                  , box.dot = list(
                      col = myPal[5]
                      , pch = 15
                      , cex = 1.2)
                  , axis.line = list(
                    col = myPal[2])
                    , strip.border = list(
                          col = myPal[2]))
       )
```

Box plot theme could go into a master theme file.

```{r means_stdevs_sales_quota, results='hide'}
# means
# pop
mn_Quo_P <- mean(KQuota)
mn_Sal_P <- mean(KSales)
mn_Tar_P <- mean(OnTarget)
kable(data.frame(
  Population_mean_KQuota = mn_Quo_P
  , Population_mean_KSales = mn_Sal_P
  , Population_mean_OnTarget = mn_Tar_P
))

# Grp A
mn_Quo_A <- mean(KQuota[Group == "A"])
mn_Sal_A <- mean(KSales[Group == "A"])
mn_Tar_A <- mean(OnTarget[Group == "A"])
kable(data.frame(
  GroupA_mean_KQuota = mn_Quo_A
  , GroupA_mean_KSales = mn_Sal_A
  , GroupA_mean_OnTarget = mn_Tar_A
))

# Grp B
mn_Quo_B <- mean(KQuota[Group == "B"])
mn_Sal_B <- mean(KSales[Group == "B"])
mn_Tar_B <- mean(OnTarget[Group == "B"])
kable(data.frame(
  GroupB_mean_KQuota = mn_Quo_B
  , GroupB_mean_KSales = mn_Sal_B
  , GroupB_mean_OnTarget = mn_Tar_B
))

# St Devs
# Pop
sd_Quo_P <- sd(KQuota)
sd_Sal_P <- sd(KSales)
sd_Tar_P <- sd(OnTarget)
kable(data.frame(
      Population_StDev_KQuota = sd_Quo_P
      , Population_StDev_KSales = sd_Sal_P
      , Population_StDev_OnTarget = sd_Tar_P
))

# Grp A
sd_Quo_A <- sd(KQuota[Group == "A"])
sd_Sal_A <- sd(KSales[Group == "A"])
sd_Tar_A <- sd(OnTarget[Group == "A"])
kable(data.frame(
      GroupA_StDev_KQuota = sd_Quo_A
      , GroupA_StDev_KSales = sd_Sal_A
      , GroupA_StDev_OnTarget = sd_Tar_A
))

# Grp B
sd_Quo_B <- sd(KQuota[Group == "B"])
sd_Sal_B <- sd(KSales[Group == "B"])
sd_Tar_B <- sd(OnTarget[Group == "B"])
kable(data.frame(
      GroupB_StDev_KQuota = sd_Quo_B
      , GroupB_StDev_KSales = sd_Sal_B
      , GroupB_StDev_OnTarget = sd_Tar_B
))
```


### Attainment / Target

```{r Exploratory_Graph_Attainment_Quota, opts.label='fig.wide'}
q <- qplot(data = raw.data, x = KQuota, y = OnTarget
      , colour = Group, alpha = I(0.5))
q <- q + geom_smooth(method = "lm", se = FALSE, size = 1.25)
q <- q + labs(list(title = "Attainment by Quota by Group with lm fit"
              , x = "Quota (1000's)", y = "On Target %")) + theme_bw()
q
```


```{r missing_var_plot, opts.label='fig.wide'}
q <- qplot(data = raw.data, x = KQuota, y = rollingSD
       , colour = Group, alpha = I(0.5))
q <- q + geom_smooth(span = 0.2, degree = 0, size = 1.25)
q <- q + labs(list(title = "Heteroskedastic Trend by Quota by Group"
              , x = "Quota (1000's)", y = "Missing variable - falling variance")) + theme_bw()
q
```

```{r linear_models}
lm.mvar <- lm(OnTarget~Group:Quota+rollingSD)
summary(lm.mvar)
```

```{r simulation_from_linear_model, opts.label='fig.wide'}
set.seed(33354)
coefs <- round(lm.mvar$coefficients,4)
raw.data$simTarget <- rnorm(n, coefs[1] + 
                               coefs[2] * rollingSD +
                             (Group == "B") * 1 * coefs[4] * Quota
                          , sd = rollingSD) + 
                      rnorm(n, sd = sd(resid(lm.mvar)))

raw.data$predict.lm.mvar <- predict(lm.mvar, raw.data)
raw.data$predict.lm.mvar.adjusted <- predict(lm.mvar, raw.data) + (Group == "B") * 4.5 + 
                      rnorm(n, sd = rollingSD)

attach(raw.data)
# root mean squared error
sqrt(mean((simTarget-OnTarget)^2))
sqrt(mean((predict.lm.mvar-OnTarget)^2))
```

```{r plot_simulated_outcome, opts.label='fig.wide'}
q <- qplot(data = raw.data
      , x = Quota, y = simTarget
      , colour = Group
      , alpha = I(0.5))
q <- q + geom_smooth(method = "lm", se = FALSE, size = 1.25)
q <- q + labs(list(title = "Simulated Attainment by Quota by Group"
              , x = "Quota (1000's)", y = "On Target %")) + theme_bw()
q
```

```{r same_from_predict, opts.label='fig.wide'}
q <- qplot(data = raw.data
      , x = Quota, y = predict.lm.mvar
      , colour = Group
      , alpha = I(0.5))
q <- q + geom_smooth(method = "lm", se = FALSE, size = 1.25)
q <- q + coord_cartesian(ylim = c(-45, 52))
q <- q + labs(list(title = "Predicted Attainment by Quota by Group"
              , x = "Quota (1000's)", y = "On Target %")) + theme_bw()
q
```

```{r plot_pred_model, opts.label='fig.wide'}
g <- ggplot(data = raw.data, aes(x = predict.lm.mvar, y = OnTarget, colour = Group), alpha = 0.5) +
  geom_point() +
  theme_bw()
g
```

```{r density, opts.label='fig.wide'}
densityplot(~OnTarget, groups = Group, bw = 3, kernel = "gaussian")
```

